In [1]:
import pandas as pd

In [38]:
data=pd.read_csv("diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [39]:
x=data.drop('Outcome',axis=1)
y=data['Outcome']

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [41]:
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier()

rfc.fit(x_train,y_train)

rfc_predict=rfc.predict(x_test)

C:\Users\RANGA\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [42]:
# Evaluating performance
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report,confusion_matrix

In [43]:
rfc_cv_score=cross_val_score(rfc,x,y,cv=10,scoring='roc_auc')

rfc_cv_score

array([0.75592593, 0.81185185, 0.82296296, 0.70592593, 0.77444444,
       0.8       , 0.81481481, 0.85925926, 0.77769231, 0.84115385])

In [44]:
print("confussion_matrix",confusion_matrix(y_test,rfc_predict))
print("classification_report",classification_report(y_test,rfc_predict))
print("rfc_cv_score",rfc_cv_score)
print("rfc_cv_score.mean",rfc_cv_score.mean())

confussion_matrix [[133  13]
 [ 43  42]]
classification_report               precision    recall  f1-score   support

           0       0.76      0.91      0.83       146
           1       0.76      0.49      0.60        85

   micro avg       0.76      0.76      0.76       231
   macro avg       0.76      0.70      0.71       231
weighted avg       0.76      0.76      0.74       231

rfc_cv_score [0.75592593 0.81185185 0.82296296 0.70592593 0.77444444 0.8
 0.81481481 0.85925926 0.77769231 0.84115385]
rfc_cv_score.mean 0.7964031339031339


In [28]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
n_estimators=[int(x) for x in np.linspace(start=200,stop=2000,num=11)]

max_features=['auto','sqrt']

max_depth=[int(x) for x in np.linspace(100,500,num=11)]

max_depth.append(None)

random_grid={'n_estimators':n_estimators,'max_features':max_features,"max_depth":max_depth}

rfc_random=RandomizedSearchCV(estimator=rfc,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                              random_state=42,n_jobs=-1)

rfc_random.fit(x_train,y_train)

print(rfc_random.best_params_)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   35.5s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  2.3min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  4.2min finished


{'n_estimators': 740, 'max_features': 'auto', 'max_depth': 140}


In [34]:
# Evaluating performance
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report,confusion_matrix

In [36]:
rfc=RandomForestClassifier(n_estimators=200,max_depth=140,max_features="sqrt")

rfc.fit(x_train,y_train)

rfc_predict=rfc.predict(x_test)
rfc_cv_score=cross_val_score(rfc,x,y,cv=10,scoring='roc_auc')

print(confusion_matrix(y_test,rfc_predict))
print("\n")
print(classification_report(y_test,rfc_predict))
print("\n")
print(rfc_cv_score)
print("\n")
print(rfc_cv_score.mean())

[[132  14]
 [ 34  51]]


              precision    recall  f1-score   support

           0       0.80      0.90      0.85       146
           1       0.78      0.60      0.68        85

   micro avg       0.79      0.79      0.79       231
   macro avg       0.79      0.75      0.76       231
weighted avg       0.79      0.79      0.79       231



[0.78592593 0.82407407 0.81666667 0.73851852 0.81481481 0.85555556
 0.8662963  0.91592593 0.815      0.84538462]


0.8278162393162394


In [49]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
5              5      116             74              0        0  25.6   
6              3       78             50             32       88  31.0   
7             10      115              0              0        0  35.3   
8              2      197             70             45      543  30.5   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
11            10      168             74              0        0  38.0   
12            10      139             80              0        0  27.1   
13             1      189             60             23      846  30.1   
14             5      166             72             19      175  25.8   
15             7      100              0              0        0  30.0   
16             0      118             84             47      230  45.8   
17             7      107             74              0        0  29.6   
18             1      103             30             38       83  43.3   
19             1      115             70             30       96  34.6   
20             3      126             88             41      235  39.3   
21             8       99             84              0        0  35.4   
22             7      196             90              0        0  39.8   
23             9      119             80             35        0  29.0   
24            11      143             94             33      146  36.6   
25            10      125             70             26      115  31.1   
26             7      147             76              0        0  39.4   
27             1       97             66             15      140  23.2   
28            13      145             82             19      110  22.2   
29             5      117             92              0        0  34.1   
..           ...      ...            ...            ...      ...   ...   
738            2       99             60             17      160  36.6   
739            1      102             74              0        0  39.5   
740           11      120             80             37      150  42.3   
741            3      102             44             20       94  30.8   
742            1      109             58             18      116  28.5   
743            9      140             94              0        0  32.7   
744           13      153             88             37      140  40.6   
745           12      100             84             33      105  30.0   
746            1      147             94             41        0  49.3   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   
752            3      108             62             24        0  26.0   
753            0      181             88             44      510  43.3   
754            8      154             78             32        0  32.4   
755            1      128             88             39      110  36.5   
756            7      137             90             41        0  32.0   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
760      

In [46]:
rfc.predict([[1,93,70,31,0,30.4,0.315,23]])

array([0], dtype=int64)

In [50]:
rfc.predict([[6,148,72,35,0,33.6,0.627,50]])

array([1], dtype=int64)

In [51]:
rfc.predict([[0,5,9,10,85,96,32,65]])

array([0], dtype=int64)