In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("shirtsize.csv")
data

Height  Weight Size
0      158      58    M
1      158      59    M
2      158      63    M
3      160      59    M
4      160      60    M
5      163      60    M
6      163      61    M
7      160      64    L
8      163      64    L
9      165      61    L
10     165      61    L
11     165      62    L
12     168      62    L
13     168      63    L
14     168      66    L
15     170      63    L
16     170      64    L
17     170      68    L

In [3]:
data.head()

Height  Weight Size
0     158      58    M
1     158      59    M
2     158      63    M
3     160      59    M
4     160      60    M

In [5]:
data.isnull().sum()

Height    0
Weight    0
Size      0
dtype: int64

In [7]:
data.isna().sum()

Height    0
Weight    0
Size      0
dtype: int64

In [9]:
data.describe()

Height     Weight
count   18.00000  18.000000
mean   164.00000  62.111111
std      4.32503   2.564208
min    158.00000  58.000000
25%    160.00000  60.250000
50%    164.00000  62.000000
75%    168.00000  63.750000
max    170.00000  68.000000

In [10]:
data.shape

(18, 3)

In [11]:
data.size

54

In [17]:
data.dtypes

Height     int64
Weight     int64
Size      object
dtype: object

In [19]:
data.head()

Height  Weight Size
0     158      58    M
1     158      59    M
2     158      63    M
3     160      59    M
4     160      60    M

In [21]:
data.count()

Height    18
Weight    18
Size      18
dtype: int64

In [26]:
x = data[['Height','Weight']]
x.size

36

In [27]:
x.shape

(18, 2)

In [28]:
x.ndim

2

In [32]:
y = pd.get_dummies(data['Size'],drop_first=True)
y

M
0   1
1   1
2   1
3   1
4   1
5   1
6   1
7   0
8   0
9   0
10  0
11  0
12  0
13  0
14  0
15  0
16  0
17  0

In [33]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=2)

In [34]:
knn.fit(x,y)

C:\Users\RANGA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=2, p=2,
           weights='uniform')

In [35]:
y_pred = knn.predict(x)

In [36]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [37]:
accuracy_score(y,y_pred)

0.9444444444444444

In [38]:
confusion_matrix(y,y_pred)

array([[11,  0],
       [ 1,  6]], dtype=int64)

Accuracy = (TP+TN)/(TP+TN+FP+FN)
print(Accuracy)

Precision = TP/(TP/FP)
print(Precision)


Recall = TP/(TP+FN)
print(Recall)

True_Positive_Rate = TP/(TP+FN)
Print(True_Positive_Rate)

False_Positive_Rate = FP/(FP+TN)
print(False_Positive_Rate)



In [39]:
from sklearn.datasets import load_iris

In [40]:
da = load_iris()
da

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [41]:
x_a = da.data
x_a

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [43]:
y_a = da.target
y_a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [44]:
y_a1 = pd.get_dummies(da.target)
y_a1

0  1  2
0    1  0  0
1    1  0  0
2    1  0  0
3    1  0  0
4    1  0  0
5    1  0  0
6    1  0  0
7    1  0  0
8    1  0  0
9    1  0  0
10   1  0  0
11   1  0  0
12   1  0  0
13   1  0  0
14   1  0  0
15   1  0  0
16   1  0  0
17   1  0  0
18   1  0  0
19   1  0  0
20   1  0  0
21   1  0  0
22   1  0  0
23   1  0  0
24   1  0  0
25   1  0  0
26   1  0  0
27   1  0  0
28   1  0  0
29   1  0  0
..  .. .. ..
120  0  0  1
121  0  0  1
122  0  0  1
123  0  0  1
124  0  0  1
125  0  0  1
126  0  0  1
127  0  0  1
128  0  0  1
129  0  0  1
130  0  0  1
131  0  0  1
132  0  0  1
133  0  0  1
134  0  0  1
135  0  0  1
136  0  0  1
137  0  0  1
138  0  0  1
139  0  0  1
140  0  0  1
141  0  0  1
142  0  0  1
143  0  0  1
144  0  0  1
145  0  0  1
146  0  0  1
147  0  0  1
148  0  0  1
149  0  0  1

[150 rows x 3 columns]

In [45]:
y_a = y_a1[0]
y_a

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    0
139    0
140    0
141    0
142    0
143    0
144    0
145    0
146    0
147    0
148    0
149    0
Name: 0, Length: 150, dtype: uint8

In [48]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [49]:
from sklearn.neighbors import KNeighborsClassifier

In [50]:
knn1=KNeighborsClassifier(n_neighbors=5)

In [51]:
knn1.fit(x_train,y_train)

C:\Users\RANGA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [52]:
y_p=knn1.predict(x_test)

In [53]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [56]:
accuracy_score(y_test,y_p)

0.6666666666666666

In [57]:
confusion_matrix(y_test,y_p)

array([[2, 1],
       [1, 2]], dtype=int64)

In [60]:
import pandas as pd